-- Raw MySQL Schema for Blog

CREATE TABLE IF NOT EXISTS User (
  id VARCHAR(191) PRIMARY KEY,
  name VARCHAR(191),
  email VARCHAR(191) UNIQUE,
  emailVerified DATETIME(3),
  image VARCHAR(191),
  password VARCHAR(191),
  role VARCHAR(191) DEFAULT 'USER',
  createdAt DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
);

CREATE TABLE IF NOT EXISTS Account (
  id VARCHAR(191) PRIMARY KEY,
  userId VARCHAR(191) NOT NULL,
  type VARCHAR(191) NOT NULL,
  provider VARCHAR(191) NOT NULL,
  providerAccountId VARCHAR(191) NOT NULL,
  refresh_token TEXT,
  access_token TEXT,
  expires_at INT,
  token_type VARCHAR(191),
  scope VARCHAR(191),
  id_token TEXT,
  session_state VARCHAR(191),
  UNIQUE KEY unique_provider (provider, providerAccountId),
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Session (
  id VARCHAR(191) PRIMARY KEY,
  sessionToken VARCHAR(191) UNIQUE NOT NULL,
  userId VARCHAR(191) NOT NULL,
  expires DATETIME(3) NOT NULL,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS VerificationToken (
  identifier VARCHAR(191) NOT NULL,
  token VARCHAR(191) UNIQUE NOT NULL,
  expires DATETIME(3) NOT NULL,
  UNIQUE KEY unique_identifier_token (identifier, token)
);

CREATE TABLE IF NOT EXISTS Category (
  id VARCHAR(191) PRIMARY KEY,
  nameEn VARCHAR(191) UNIQUE NOT NULL,
  nameHi VARCHAR(191),
  nameGu VARCHAR(191),
  slug VARCHAR(191) UNIQUE NOT NULL,
  isTravel BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS Tag (
  id VARCHAR(191) PRIMARY KEY,
  name VARCHAR(191) UNIQUE NOT NULL,
  slug VARCHAR(191) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS State (
  id VARCHAR(191) PRIMARY KEY,
  nameEn VARCHAR(191) UNIQUE NOT NULL,
  nameHi VARCHAR(191),
  nameGu VARCHAR(191),
  lat FLOAT,
  lng FLOAT
);

CREATE TABLE IF NOT EXISTS District (
  id VARCHAR(191) PRIMARY KEY,
  nameEn VARCHAR(191) NOT NULL,
  nameHi VARCHAR(191),
  nameGu VARCHAR(191),
  lat FLOAT,
  lng FLOAT,
  stateId VARCHAR(191) NOT NULL,
  UNIQUE KEY unique_name_state (nameEn, stateId),
  FOREIGN KEY (stateId) REFERENCES State(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Taluka (
  id VARCHAR(191) PRIMARY KEY,
  nameEn VARCHAR(191) NOT NULL,
  nameHi VARCHAR(191),
  nameGu VARCHAR(191),
  lat FLOAT,
  lng FLOAT,
  districtId VARCHAR(191) NOT NULL,
  UNIQUE KEY unique_name_district (nameEn, districtId),
  FOREIGN KEY (districtId) REFERENCES District(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Village (
  id VARCHAR(191) PRIMARY KEY,
  nameEn VARCHAR(191) NOT NULL,
  nameHi VARCHAR(191),
  nameGu VARCHAR(191),
  lat FLOAT NOT NULL,
  lng FLOAT NOT NULL,
  talukaId VARCHAR(191) NOT NULL,
  UNIQUE KEY unique_name_taluka (nameEn, talukaId),
  FOREIGN KEY (talukaId) REFERENCES Taluka(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Post (
  id VARCHAR(191) PRIMARY KEY,
  titleEn VARCHAR(191) NOT NULL,
  titleHi VARCHAR(191),
  titleGu VARCHAR(191),
  slug VARCHAR(191) UNIQUE NOT NULL,
  excerptEn TEXT NOT NULL,
  excerptHi TEXT,
  excerptGu TEXT,
  contentEn LONGTEXT NOT NULL,
  contentHi LONGTEXT,
  contentGu LONGTEXT,
  coverImage VARCHAR(191) NOT NULL,
  bannerImage VARCHAR(191),
  published BOOLEAN DEFAULT TRUE,
  isFeatured BOOLEAN DEFAULT FALSE,
  isTrending BOOLEAN DEFAULT FALSE,
  isEditorPick BOOLEAN DEFAULT FALSE,
  galleryImages JSON,
  readingTime VARCHAR(191) NOT NULL,
  lat FLOAT,
  lng FLOAT,
  createdAt DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  authorId VARCHAR(191) NOT NULL,
  stateId VARCHAR(191),
  districtId VARCHAR(191),
  talukaId VARCHAR(191),
  villageId VARCHAR(191),
  FOREIGN KEY (authorId) REFERENCES User(id),
  FOREIGN KEY (stateId) REFERENCES State(id),
  FOREIGN KEY (districtId) REFERENCES District(id),
  FOREIGN KEY (talukaId) REFERENCES Taluka(id),
  FOREIGN KEY (villageId) REFERENCES Village(id)
);

CREATE TABLE IF NOT EXISTS Comment (
  id VARCHAR(191) PRIMARY KEY,
  content TEXT NOT NULL,
  createdAt DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  postId VARCHAR(191) NOT NULL,
  userId VARCHAR(191) NOT NULL,
  FOREIGN KEY (postId) REFERENCES Post(id) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `Like` (
  postId VARCHAR(191) NOT NULL,
  userId VARCHAR(191) NOT NULL,
  PRIMARY KEY (postId, userId),
  FOREIGN KEY (postId) REFERENCES Post(id) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SavedPost (
  postId VARCHAR(191) NOT NULL,
  userId VARCHAR(191) NOT NULL,
  PRIMARY KEY (postId, userId),
  FOREIGN KEY (postId) REFERENCES Post(id) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES User(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Subscriber (
  id VARCHAR(191) PRIMARY KEY,
  email VARCHAR(191) UNIQUE NOT NULL,
  createdAt DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3),
  isActive BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS _CategoryToPost (
  A VARCHAR(191) NOT NULL,
  B VARCHAR(191) NOT NULL,
  UNIQUE KEY unique_AB (A, B),
  INDEX (B),
  FOREIGN KEY (A) REFERENCES Category(id) ON DELETE CASCADE,
  FOREIGN KEY (B) REFERENCES Post(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS _PostToTag (
  A VARCHAR(191) NOT NULL,
  B VARCHAR(191) NOT NULL,
  UNIQUE KEY unique_AB (A, B),
  INDEX (B),
  FOREIGN KEY (A) REFERENCES Post(id) ON DELETE CASCADE,
  FOREIGN KEY (B) REFERENCES Tag(id) ON DELETE CASCADE
);
